name: Matrix demo

on: 
  workflow_dispatch:
jobs:
  run-matrix:
    environment: "dev"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [1, 2, 3]
      max-parallel: 1
    steps:
      - name: Matrix
        id: demo-matrix
        run: |
          echo "Print github.event.ref: ${{ github.event.ref }}"
          echo "Matrix item: ${{ matrix.step }}"
          echo "Environmet variable: ${{ vars.TEST_KEY }}"
          echo "REPO var: ${{ vars.REPO_VAR }}"
          echo "Secret repo: ${{ secrets.REPO_KEY }}"
          echo "Secret env: ${{ secrets.ENV_KEY }}"
          echo "Secret variable: ${{ secrets.API_KEY }}"
