name: Demo schedule

on:
  workflow_dispatch:
#  schedule:
#    - cron: "*/30 * * * *" 

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date
        id: print_date
        run: |
          echo $(date)
