name: Demo schedule

on:
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date
        id: print_date
        run: |
          echo $(date)